// Register Action
export const HTTP_REGISTER_FETCHING = 'HTTP_REGISTER_FETCHING';
export const HTTP_REGISTER_SUCCESS = 'HTTP_REGISTER_SUCCESS';
export const HTTP_REGISTER_FAILED = 'HTTP_REGISTER_FAILED';

// Login Action
export const HTTP_LOGIN_FETCHING = 'HTTP_LOGIN_FETCHING';
export const HTTP_LOGIN_SUCCESS = 'HTTP_LOGIN_SUCCESS';
export const HTTP_LOGIN_FAILED = 'HTTP_LOGIN_FAILED';
