// Register Action
export const HTTP_REGISTER_FETCHING = 'HTTP_REGISTER_FETCHING';
export const HTTP_REGISTER_SUCCESS = 'HTTP_REGISTER_SUCCESS';
export const HTTP_REGISTER_FAILED = 'HTTP_REGISTER_FAILED';

// Login Action
export const HTTP_LOGIN_FETCHING = 'HTTP_LOGIN_FETCHING';
export const HTTP_LOGIN_SUCCESS = 'HTTP_LOGIN_SUCCESS';
export const HTTP_LOGIN_FAILED = 'HTTP_LOGIN_FAILED';

// Stock Action
export const HTTP_STOCK_FETCHING = 'HTTP_STOCK_FETCHING';
export const HTTP_STOCK_SUCCESS = 'HTTP_STOCK_SUCCESS';
export const HTTP_STOCK_FAILED = 'HTTP_STOCK_FAILED';
export const HTTP_STOCK_INITIALED = 'HTTP_STOCK_INITIALED';
